language: go
os: linux-ppc64le
sudo: required

go:
  - 1.x
go_import_path: k8s.io/minikube

install:

script:
  - cd ..
  - rm -rf -f bazel
  - git clone https://github.com/bazelbuild/bazel.git
  - cd bazel
  - wget https://oplab9.parqtec.unicamp.br/pub/ppc64el/bazel/ubuntu_14.04/bazel_bin_ppc64le_0.21.0
  - mv bazel_bin_ppc64le_0.21.0 bazel 
  - chmod +x bazel 
  - ./bazel build 
