language: java

os: linux-ppc64le
env: BAZEL_VERSION=0.23.0

matrix:
    include:
        os: linux-ppc64le
            - linux-ppc64le
              env: BAZEL_VERSION=0.23.0
            - linux-ppc64le
              env: BAZEL_VERSION=0.22.0

sudo: required

jdk:
  - openjdk8

before_install:
  - sudo apt-get update
  - sudo apt-get install -y -qq build-essential python zip unzip

env:
  - EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk"

script:
  - wget https://github.com/bazelbuild/bazel/releases/download/$BAZEL_VERSION/bazel-$BAZEL_VERSION-dist.zip
  - unzip ./bazel-$BAZEL_VERSION-dist -d ./bazel
  - cd ./bazel
  - ./compile.sh
  - ls ./output
