language: java

os: linux-ppc64le

sudo: required

jdk:
  - openjdk9

before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential python zip unzip

script:
  - git clone https://github.com/bazelbuild/bazel.git
  - cd ./bazel
  - git checkout -t origin/release-0.23.1
  - java -version
  - java -XshowSettings:properties -version 2>&1 > /dev/null | grep 'java.home'
  - ./bazel build --host_javabase=@bazel_tools//tools/jdk:absolute_javabase --define=ABSOLUTE_JAVABASE=/usr/lib/jvm/java-8-openjdk-ppc64el/ //src:bazel
