language: java

os: linux-ppc64le

sudo: required

jdk:
  - openjdk8

before_install:
  - sudo apt-get update
  - sudo apt-get install -y -qq build-essential python zip unzip

env:
  - EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk"

script:
  - git clone https://github.com/bazelbuild/bazel.git
  - cd ./bazel
  - git checkout -t origin/release-0.23.1
  - ./compile.sh
